[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# This is the critical part for fixing 404 errors with SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

[functions]
  node_bundler = "esbuild"
  # This directory is critical for Astro SSR
  directory = "functions"
  included_files = ["dist/**"]
